# Generated by Django 4.0.3 on 2022-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('annee_parution', models.CharField(max_length=100)),
                ('nombre_episodes', models.IntegerField()),
                ('url_anime', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
