# Generated by Django 4.0.3 on 2022-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationanime', '0002_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url_site',
            field=models.CharField(max_length=150),
        ),
    ]
