# Generated by Django 4.0.4 on 2022-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationanime', '0003_alter_site_url_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tarif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
